name: Compile Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Compile with Maven
      run: |
        cd app
        mvn clean compile
        
    - name: Run tests
      run: |
        cd app
        mvn test
        
    - name: Build JAR
      run: |
        cd app
        mvn package -DskipTests
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backend-jar
        path: app/target/*.jar

